name: dart_mongo
description: A command-line application that talks to a MongoDB database.
version: 1.0.0
homepage: https://www.creativebracket.com
author: Jermaine Oppong <name@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  mongo_dart: ^0.3.6
  http_server: ^0.9.8+1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
